/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.gfxmonk.android.pagefeed;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
    }
    public static final class id {
        public static final int sync_state=0x7f050001;
        public static final int url=0x7f050000;
    }
    public static final class layout {
        public static final int url_item=0x7f030000;
        public static final int url_list=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
